version: "3"

volumes:
  cacheData:
    external: true
  dbData:
    external: true
  influxdbData:
    external: true

services:
  cache:
    restart: unless-stopped
    image: redis:7.0.7-alpine
    command: redis-server --loglevel warning
    ports:
      - 6379:6379
    volumes:
      - cacheData:/data
    container_name: Cache

  postgres:
      restart: unless-stopped
      image: postgres:15.2-alpine
      environment:
        - POSTGRES_USER=disstat
        - POSTGRES_PASSWORD=AQwrMb4WzngykR9v
        - POSTGRES_DB=disstat
      ports:
        - 5432:5432
      volumes:
        - ./schema.postgresql.sql:/docker-entrypoint-initdb.d/schema.postgresql.sql:ro
        - dbData:/var/lib/postgresql/data
      container_name: DB
  
  app:
    restart: unless-stopped
    build: 
      context: ./siteSrc
      dockerfile: Dockerfile
    container_name: app
    ports:
      - '80:3000'
    depends_on:
      - postgres
      - cache
      - influxdb

  bot:
    restart: unless-stopped
    build: 
      context: ./bot
      dockerfile: Dockerfile
    container_name: bot
    depends_on:
      - postgres
      - cache
      - influxdb

  tasks:
    restart: unless-stopped
    build: 
      context: ./tasks
      dockerfile: Dockerfile
    container_name: tasks
    depends_on:
      - postgres
      # - cache
      # - influxdb

  influxdb:
    image: influxdb:2.7.1-alpine
    ports:
      - '8086:8086'
    container_name: influxdb
    volumes:
      - influxdbData:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_ORG=disstat
      - DOCKER_INFLUXDB_INIT_BUCKET=defaultBucket
      - DOCKER_INFLUXDB_INIT_USERNAME=disStatAdmin
      - 'DOCKER_INFLUXDB_INIT_PASSWORD=6#Le0zTjR0Q2'
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=yh3dMn8sXX09umUdz!ykW3m&d2PN9s
