const globals = require("globals")

const unicorn = require("eslint-plugin-unicorn")
const sonarjs = require("eslint-plugin-sonarjs")
const stylistic = require("@stylistic/eslint-plugin")
const vue = require("eslint-plugin-vue")
const tsParser = require("@typescript-eslint/parser")

const config = {
	linterOptions: {
		reportUnusedDisableDirectives: "error"
	},
	languageOptions: {
		globals: {
			...globals.node,
			defineNuxtConfig: "readonly",
			defineNuxtPlugin: "readonly",
			defineEventHandler: "readonly",
			useRuntimeConfig: "readonly",
			useFetch: "readonly"
		}
	},
	plugins: {
		unicorn,
		sonarjs,
		"@stylistic": stylistic,
		vue
	},
	rules: {
		"array-callback-return": 2,
		"block-scoped-var": 2,
		"default-case-last": 2,
		"default-param-last": 2,
		"dot-notation": 2,
		"func-name-matching": 2,
		"no-array-constructor": 2,
		"no-compare-neg-zero": 2,
		"no-const-assign": 2,
		"no-constructor-return": 2,
		"no-dupe-args": 2,
		"no-dupe-keys": 2,
		"no-duplicate-case": 2,
		"no-div-regex": 2,
		"no-eq-null": 2,
		"no-extra-bind": 2,
		"no-extend-native": 2,
		"no-empty-pattern": 2,
		"no-duplicate-imports": 2,
		"no-fallthrough": 2,
		"no-func-assign": 2,
		"no-import-assign": 2,
		"no-invalid-regexp": 2,
		"no-invalid-this": 2,
		"no-implicit-coercion": [2, {
			string: false
		}],
		"no-implied-eval": 2,
		"no-loss-of-precision": 2,
		"no-multi-assign": 2,
		"no-negated-condition": 2,
		"no-new-native-nonconstructor": 2,
		"no-new-object": 2,
		"no-obj-calls": 2,
		"no-self-assign": 2,
		"no-unreachable": 1,
		"no-unreachable-loop": 2,
		"no-unsafe-finally": 2,
		"no-unused-vars": 2,
		"no-useless-computed-key": 2,
		"no-useless-rename": 2,
		"no-useless-escape": 2,
		"no-unused-expressions": 2,
		"no-useless-return": 2,
		"no-useless-call": 2,
		"no-use-before-define": [2, {
			functions: false
		}],
		"no-useless-concat": 2,
		"no-useless-backreference": 2,
		"no-useless-catch": 2,
		"no-unneeded-ternary": 2,
		"no-undef": [2, {
			typeof: true
		}],
		"no-undef-init": 2,
		"no-useless-constructor": 2,
		"no-redeclare": 2,
		"no-shadow-restricted-names": 2,
		"no-empty-static-block": 2,
		"no-throw-literal": 2,
		"no-template-curly-in-string": 2,
		"no-unsafe-optional-chaining": 2,
		"no-unmodified-loop-condition": 2,
		"no-promise-executor-return": 2,
		"no-warning-comments": 1,
		"no-var": 2,
		"no-new-func": 2,
		"no-new-wrappers": 2,
		"no-multi-str": 2,
		"no-shadow": [2, {
			builtinGlobals: false
		}],
		"no-self-compare": 2,
		"no-regex-spaces": 2,
		"no-constant-binary-expression": 2,
		"no-sequences": 2,
		"no-irregular-whitespace": [2, {
			skipRegExps: true
		}],
		"no-constant-condition": 2,
		"no-undefined": 2,
		"no-lone-blocks": 2,
		"object-shorthand": 2,
		"prefer-arrow-callback": 2,
		"prefer-const": 2,
		"use-isnan": 2,
		"valid-typeof": 2,

		"@stylistic/array-bracket-spacing": 2,
		"@stylistic/comma-style": 2,
		"@stylistic/computed-property-spacing": 2,
		"@stylistic/dot-location": [2, "property"],
		"@stylistic/function-call-spacing": 2,
		"@stylistic/generator-star-spacing": 2,
		"@stylistic/keyword-spacing": 1,
		"@stylistic/new-parens": 2,
		"@stylistic/no-mixed-operators": [2, {
			groups: [["*", "/"], ["+", "-"]]
		}],
		"@stylistic/no-floating-decimal": 2,
		"@stylistic/no-whitespace-before-property": 1,
		"@stylistic/padded-blocks": [2, "never"],
		"@stylistic/rest-spread-spacing": 2,
		"@stylistic/space-in-parens": 2,
		"@stylistic/space-unary-ops": 2,
		"@stylistic/yield-star-spacing": 2,

		"unicorn/empty-brace-spaces": 2,
		"unicorn/error-message": 2,
		"unicorn/new-for-builtins": 2,
		"unicorn/consistent-destructuring": 2,
		"unicorn/consistent-function-scoping": 2,
		"unicorn/no-array-method-this-argument": 2,
		"unicorn/no-lonely-if": 2,
		"unicorn/no-instanceof-array": 2,
		"unicorn/no-nested-ternary": 2,
		"unicorn/no-new-buffer": 2,
		"unicorn/no-console-spaces": 2,
		"unicorn/no-for-loop": 2,
		"unicorn/no-useless-undefined": 2,
		"unicorn/no-zero-fractions": 2,
		"unicorn/no-unreadable-iife": 2,
		"unicorn/no-unnecessary-await": 2,
		"unicorn/no-unreadable-array-destructuring": 2,
		"unicorn/no-useless-switch-case": 2,
		"unicorn/no-typeof-undefined": 2,
		"unicorn/no-useless-fallback-in-spread": 2,
		"unicorn/no-useless-length-check": 2,
		"unicorn/no-useless-spread": 2,
		"unicorn/no-useless-promise-resolve-reject": 2,
		"unicorn/prefer-array-find": 2,
		"unicorn/prefer-array-index-of": 2,
		"unicorn/prefer-includes": 2,
		"unicorn/prefer-logical-operator-over-ternary": 2,
		"unicorn/prefer-date-now": 2,
		"unicorn/prefer-default-parameters": 2,
		"unicorn/prefer-array-some": 2,
		"unicorn/prefer-blob-reading-methods": 2,
		"unicorn/prefer-at": 2,
		"unicorn/prefer-optional-catch-binding": 2,
		"unicorn/prefer-regexp-test": 2,
		"unicorn/prefer-set-has": 2,
		"unicorn/prefer-set-size": 2,
		"unicorn/prefer-negative-index": 2,
		"unicorn/prefer-node-protocol": 2,
		"unicorn/prefer-prototype-methods": 2,
		"unicorn/prefer-string-trim-start-end": 2,
		"unicorn/prefer-string-starts-ends-with": 2,
		"unicorn/require-number-to-fixed-digits-argument": 2,
		"unicorn/switch-case-braces": [2, "avoid"],
		"unicorn/text-encoding-identifier-case": 2,

		"sonarjs/no-extra-arguments": 2,
		"sonarjs/no-empty-collection": 2,
		"sonarjs/no-element-overwrite": 2,
		"sonarjs/no-use-of-empty-return-value": 2,
		"sonarjs/no-all-duplicated-branches": 2,
		"sonarjs/no-ignored-return": 2,
		"sonarjs/no-identical-expressions": 2,
		"sonarjs/no-one-iteration-loop": 2,
		"sonarjs/non-existent-operator": 2,
		"sonarjs/no-redundant-boolean": 2,
		"sonarjs/no-unused-collection": 2,
		"sonarjs/prefer-immediate-return": 2,
		"sonarjs/no-inverted-boolean-check": 2,
		"sonarjs/no-redundant-jump": 2,
		"sonarjs/no-same-line-conditional": 2,
		"sonarjs/prefer-object-literal": 2,
		"sonarjs/no-collection-size-mischeck": 2,
		"sonarjs/prefer-while": 2,
		"sonarjs/no-gratuitous-expressions": 2,
		"sonarjs/no-duplicated-branches": 2,

		// Priority A: Essential (Error Prevention)
		"vue/multi-word-component-names": 2,
		"vue/no-async-in-computed-properties": 2,
		"vue/no-child-content": 2,
		"vue/no-computed-properties-in-data": 2,
		"vue/no-custom-modifiers-on-v-model": 2,
		"vue/no-deprecated-data-object-declaration": 2,
		"vue/no-deprecated-destroyed-lifecycle": 2,
		"vue/no-deprecated-dollar-listeners-api": 2,
		"vue/no-deprecated-dollar-scopedslots-api": 2,
		"vue/no-deprecated-events-api": 2,
		"vue/no-deprecated-filter": 2,
		"vue/no-deprecated-functional-template": 2,
		"vue/no-deprecated-html-element-is": 2,
		"vue/no-deprecated-inline-template": 2,
		"vue/no-deprecated-props-default-this": 2,
		"vue/no-deprecated-router-link-tag-prop": 2,
		"vue/no-deprecated-scope-attribute": 2,
		"vue/no-deprecated-slot-attribute": 2,
		"vue/no-deprecated-slot-scope-attribute": 2,
		"vue/no-deprecated-v-bind-sync": 2,
		"vue/no-deprecated-v-is": 2,
		"vue/no-deprecated-v-on-native-modifier": 2,
		"vue/no-deprecated-v-on-number-modifiers": 2,
		"vue/no-deprecated-vue-config-keycodes": 2,
		"vue/no-dupe-keys": 2,
		"vue/no-dupe-v-else-if": 2,
		"vue/no-duplicate-attributes": 2,
		"vue/no-export-in-script-setup": 2,
		"vue/no-expose-after-await": 2,
		"vue/no-lifecycle-after-await": 2,
		"vue/no-multiple-template-root": 2,
		"vue/no-mutating-props": 2,
		"vue/no-parsing-error": 2,
		"vue/no-ref-as-operand": 2,
		"vue/no-reserved-component-names": 2,
		"vue/no-reserved-keys": 2,
		"vue/no-reserved-props": 2,
		"vue/no-shared-component-data": 2,
		"vue/no-side-effects-in-computed-properties": 2,
		"vue/no-template-key": 2,
		"vue/no-textarea-mustache": 2,
		"vue/no-unused-components": 2,
		"vue/no-unused-vars": 2,
		"vue/no-use-computed-property-like-method": 2,
		"vue/no-use-v-if-with-v-for": 2,
		"vue/no-useless-template-attributes": 2,
		"vue/no-v-for-template-key-on-child": 2,
		"vue/no-v-for-template-key": 2,
		"vue/no-v-model-argument": 2,
		"vue/no-v-text-v-html-on-component": 2,
		"vue/no-watch-after-await": 2,
		"vue/prefer-import-from-vue": 2,
		"vue/require-component-is": 2,
		"vue/require-prop-type-constructor": 2,
		"vue/require-render-return": 2,
		"vue/require-slots-as-functions": 2,
		"vue/require-toggle-inside-transition": 2,
		"vue/require-v-for-key": 2,
		"vue/require-valid-default-prop": 2,
		"vue/return-in-computed-property": 2,
		"vue/return-in-emits-validator": 2,
		"vue/use-v-on-exact": 2,
		"vue/valid-attribute-name": 2,
		"vue/valid-define-emits": 2,
		"vue/valid-define-props": 2,
		"vue/valid-model-definition": 2,
		"vue/valid-next-tick": 2,
		"vue/valid-template-root": 2,
		"vue/valid-v-bind-sync": 2,
		"vue/valid-v-bind": 2,
		"vue/valid-v-cloak": 2,
		"vue/valid-v-else-if": 2,
		"vue/valid-v-else": 2,
		"vue/valid-v-for": 2,
		"vue/valid-v-html": 2,
		"vue/valid-v-if": 2,
		"vue/valid-v-is": 2,
		"vue/valid-v-memo": 2,
		"vue/valid-v-model": 2,
		"vue/valid-v-on": 2,
		"vue/valid-v-once": 2,
		"vue/valid-v-pre": 2,
		"vue/valid-v-show": 2,
		"vue/valid-v-slot": 2,
		"vue/valid-v-text": 2,
		"vue/no-arrow-functions-in-watch": 2,

		// Priority B: Strongly Recommended (Improving Readability)
		"vue/attribute-hyphenation": 2,
		"vue/first-attribute-linebreak": 2,
		"vue/html-closing-bracket-newline": 2,
		"vue/html-closing-bracket-spacing": 2,
		"vue/html-end-tags": 2,
		"vue/html-indent": 2,
		"vue/html-quotes": 2,
		"vue/html-self-closing": 2,
		"vue/max-attributes-per-line": 2,
		"vue/multiline-html-element-content-newline": 2,
		"vue/mustache-interpolation-spacing": 2,
		"vue/no-multi-spaces": 2,
		"vue/no-spaces-around-equal-signs-in-attribute": 2,
		"vue/no-template-shadow": 2,
		"vue/one-component-per-file": 2,
		"vue/prop-name-casing": 2,
		"vue/require-default-prop": 2,
		"vue/require-explicit-emits": 2,
		"vue/require-prop-types": 2,
		"vue/singleline-html-element-content-newline": 2,
		"vue/v-bind-style": 2,
		"vue/v-on-event-hyphenation": 2,
		"vue/v-on-style": 2,
		"vue/v-slot-style": 2
	}
}

module.exports = [
	{
		ignores: ["siteSrc/.nuxt/", "siteSrc/.output/"]
	},
	config,
	{
		...config,
		files: ["**/*.ts", "**/*.mts"],
		ignores: ["siteSrc/server/vite-node.d.mts"],
		languageOptions: {
			...config.languageOptions,
			parser: tsParser
		}
	},
	{
		...config,
		files: ["**/*.vue"]
	}
]
