name: Upgrade site NPM packages

on:
  workflow_dispatch:

  schedule:
    - cron:  "0 0 * * 0"

jobs:
  upgrade-packages:
    name: Upgrade packages

    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Set up Node.js ⚙️
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
          
      - name: Upgrade packages 🔀
        run: npm -g i npm-check-updates
        
      - name: Upgrade packages 🔀
        run: |
          cd siteSrc/
          ncu -u

      - name: Commit and create PR 🔀
        uses: peter-evans/create-pull-request@v3
        with:
          title: 'build(deps): Upgrade site NPM packages (automated)'
          branch: 'build-deps-upgrade-site-npm-packages-automated'
          commit-message: 'build(deps): upgrade NPM packages (automated)'
